language: ruby
rvm:
	- 1.9.3
env:
	- DB=postgresql
before_script:
	- rake db:create
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake scrape:courses --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
# bundler_args: --binstubs=./bundler_stubs