##
##  General settings
##
phonegap_path:             '~/Development/phonegap-2.7.0'
api_server:                'http://coursica.herokuapp.com'

##  Android settings
android:
   package:                'com.northwestern.courisca'
